"""add role to user

Revision ID: 96be9e48b6fc
Revises: 6997be457447
Create Date: 2026-09-26 18:03:21.709214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96be9e48b6fc'
down_revision: Union[str, Sequence[str], None] = '6997be457447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
op.add_column(
    'user',
    sa.Column(
        'is_active',
        sa.Boolean(),
        nullable=False,
        server_default=sa.true()
    )
)

op.add_column(
    'user',
    sa.Column(
        'role',
        sa.String(length=50),
        nullable=False,
        server_default='user'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
